# Generated by Django 6.0.4 on 2026-04-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_attendance_in_photo_attendance_in_photo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processentry',
            name='reference_numbers',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
